SELECT DISTINCT DEPTNO
FROM EMP;
SELECT DISTINCT "JOB", "DEPTNO"
FROM EMP;
SELECT ALL "JOB", "DEPTNO"
FROM EMP;

-- 열에 연산식 사용하여 출력
SELECT "ENAME", "SAL", "COMM", SAL*12+COMM AS "ANSWER"
FROM EMP;

-- 열에 별칭을 지정한다.
SELECT ENAME AS 사원명, SAL AS 급여, COMM AS 추가수당, SAL*12+COMM AS 총합
FROM EMP;

SELECT *
FROM EMP
ORDER BY SAL; --오름차 정렬

SELECT ENAME, JOB --3순위
FROM EMP --1순위
WHERE JOB = 'SALESMAN'; --2순위

SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO = 30;

-- AND(그리고) / OR(또는)
-- 2가지 이상의 조건을 필터링할 경우 사용한다.

SELECT *
FROM EMP
WHERE EMPNO = 7499 AND DEPTNO = 30;